// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: todo.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TodoHandlerClient is the client API for TodoHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TodoHandlerClient interface {
	GetTodoDelivery(ctx context.Context, in *SingleRequest, opts ...grpc.CallOption) (*TodoResponse, error)
}

type todoHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoHandlerClient(cc grpc.ClientConnInterface) TodoHandlerClient {
	return &todoHandlerClient{cc}
}

func (c *todoHandlerClient) GetTodoDelivery(ctx context.Context, in *SingleRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := c.cc.Invoke(ctx, "/TodoHandler/GetTodoDelivery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoHandlerServer is the server API for TodoHandler service.
// All implementations must embed UnimplementedTodoHandlerServer
// for forward compatibility
type TodoHandlerServer interface {
	GetTodoDelivery(context.Context, *SingleRequest) (*TodoResponse, error)
	mustEmbedUnimplementedTodoHandlerServer()
}

// UnimplementedTodoHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedTodoHandlerServer struct {
}

func (UnimplementedTodoHandlerServer) GetTodoDelivery(context.Context, *SingleRequest) (*TodoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodoDelivery not implemented")
}
func (UnimplementedTodoHandlerServer) mustEmbedUnimplementedTodoHandlerServer() {}

// UnsafeTodoHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoHandlerServer will
// result in compilation errors.
type UnsafeTodoHandlerServer interface {
	mustEmbedUnimplementedTodoHandlerServer()
}

func RegisterTodoHandlerServer(s grpc.ServiceRegistrar, srv TodoHandlerServer) {
	s.RegisterService(&TodoHandler_ServiceDesc, srv)
}

func _TodoHandler_GetTodoDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoHandlerServer).GetTodoDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TodoHandler/GetTodoDelivery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoHandlerServer).GetTodoDelivery(ctx, req.(*SingleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TodoHandler_ServiceDesc is the grpc.ServiceDesc for TodoHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TodoHandler",
	HandlerType: (*TodoHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodoDelivery",
			Handler:    _TodoHandler_GetTodoDelivery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
